#
# Copyright (c) 2020 Microsoft and others.
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#

# Build your hawkBit Extensions and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/java
# https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema
# https://docs.microsoft.com/en-us/azure/devops/pipelines/release/caching?view=azure-devops#maven

pool:
  vmImage: "ubuntu-18.04"

jobs:
  - job:
    displayName: MYSQL
    strategy:
      matrix:
        java-8 MYSQL-5.6:
          jdkVersionOption: "1.8"
          dbVersion: "5.6"
        java-11 MYSQL-5.6:
          jdkVersionOption: "1.11"
          dbVersion: "5.6"
        java-8 MYSQL-5.7:
          jdkVersionOption: "1.8"
          dbVersion: "5.7"
        java-11 MYSQL-5.7:
          jdkVersionOption: "1.11"
          dbVersion: "5.7"
    steps:
      - script: "docker run --name mysql -p 3306:3306 -e MYSQL_ROOT_PASSWORD=8236472364 -e MYSQL_DATABASE=hawkbit -d mysql:$(dbVersion)"
        displayName: "Setup MYSQL Database docker instance"
      - template: maven-template.yml
        parameters:
          mavenGoals: "package license:check -Dspring.jpa.database=MYSQL -Dspring.datasource.driverClassName=org.mariadb.jdbc.Driver -Dspring.datasource.url=jdbc:mysql://localhost:3306/hawkbit -Dspring.datasource.username=root -Dspring.datasource.password=8236472364"
          jdkVersionOption: $(jdkVersionOption)
  - job:
    displayName: MSSQL
    strategy:
      matrix:
        java-8 MSSQL-2017:
          jdkVersionOption: "1.8"
          dbVersion: "2017-latest"
        java-11 MSSQL-2017:
          jdkVersionOption: "1.11"
          dbVersion: "2017-latest"
        java-8 MSSQL-2019:
          jdkVersionOption: "1.8"
          dbVersion: "2019-latest"
        java-11 MSSQL-2019:
          jdkVersionOption: "1.11"
          dbVersion: "2019-latest"
    steps:
      - script: |
          docker run --name sql1 -p 1433:1433 -e ACCEPT_EULA=Y -e SA_PASSWORD=1234567890. -d mcr.microsoft.com/mssql/server:$(dbVersion)
          docker exec sql1 /opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P "1234567890." -Q "CREATE DATABASE hawkbit"
        displayName: "Setup MSSQL Database docker instance"
      - template: maven-template.yml
        parameters:
          mavenGoals: "package license:check -Dspring.jpa.database=SQL_SERVER -Dspring.datasource.url=jdbc:sqlserver://localhost:1433;database=hawkbit -Dspring.datasource.username=SA -Dspring.datasource.password=1234567890. -Dspring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver"
          jdkVersionOption: $(jdkVersionOption)
